---
title: "Rescue Mission"
type: "challenge"
description: "Build a website like stackoverflow.com for posting questions and answers."
visibility: "assign"
tags: "rails"
ignore:
- "rescue-mission.md"
